# Generated by Django 4.2.15 on 2024-10-11 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_1', models.FileField(blank=True, null=True, upload_to='famInfos/')),
                ('image_1_thumbnail', models.ImageField(blank=True, null=True, upload_to='famInfos/thumbnails/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='famInfos/')),
                ('image_2_thumbnail', models.ImageField(blank=True, null=True, upload_to='famInfos/thumbnails/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='famInfos/')),
                ('image_3_thumbnail', models.ImageField(blank=True, null=True, upload_to='famInfos/thumbnails/')),
                ('image_4', models.FileField(blank=True, null=True, upload_to='famInfos/')),
                ('image_4_thumbnail', models.ImageField(blank=True, null=True, upload_to='famInfos/thumbnails/')),
                ('family_1', models.CharField(choices=[('kempe', 'Stammbaum Kempe'), ('huenten', 'Stammbaum Hünten')], max_length=100, verbose_name='Stammbaum 1')),
                ('family_2', models.CharField(blank=True, choices=[('kempe', 'Stammbaum Kempe'), ('huenten', 'Stammbaum Hünten')], max_length=50, null=True, verbose_name='Stammbaum 2')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
