# Generated by Django 4.2.15 on 2025-08-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famInfos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faminfo',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, upload_to='famInfos/pdfs/'),
        ),
        migrations.AddField(
            model_name='faminfo',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to='famInfos/pdfs/'),
        ),
        migrations.AddField(
            model_name='faminfo',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, upload_to='famInfos/pdfs/'),
        ),
        migrations.AddField(
            model_name='faminfo',
            name='pdf_4',
            field=models.FileField(blank=True, null=True, upload_to='famInfos/pdfs/'),
        ),
    ]
