# Generated by Django 4.2.15 on 2025-08-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famInfos', '0002_faminfo_pdf_1_faminfo_pdf_2_faminfo_pdf_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faminfo',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, upload_to='famInfos/'),
        ),
        migrations.AlterField(
            model_name='faminfo',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to='famInfos/'),
        ),
        migrations.AlterField(
            model_name='faminfo',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, upload_to='famInfos/'),
        ),
        migrations.AlterField(
            model_name='faminfo',
            name='pdf_4',
            field=models.FileField(blank=True, null=True, upload_to='famInfos/'),
        ),
    ]
