# Generated by Django 4.2.15 on 2025-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famInfos', '0003_alter_faminfo_pdf_1_alter_faminfo_pdf_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faminfo',
            name='pdf_1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faminfo',
            name='pdf_2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faminfo',
            name='pdf_3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faminfo',
            name='pdf_4_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
