# Generated by Django 4.2.15 on 2025-08-26 16:40

from django.db import migrations, models
import famInfos.models


class Migration(migrations.Migration):

    dependencies = [
        ('famInfos', '0004_faminfo_pdf_1_name_faminfo_pdf_2_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faminfo',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, upload_to=famInfos.models.pdf_upload_to),
        ),
        migrations.AlterField(
            model_name='faminfo',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to=famInfos.models.pdf_upload_to),
        ),
        migrations.AlterField(
            model_name='faminfo',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, upload_to=famInfos.models.pdf_upload_to),
        ),
        migrations.AlterField(
            model_name='faminfo',
            name='pdf_4',
            field=models.FileField(blank=True, null=True, upload_to=famInfos.models.pdf_upload_to),
        ),
    ]
