# Generated by Django 5.2.16 on 2026-08-07 14:34

import famInfos.models
import utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famInfos', '0005_alter_faminfo_pdf_1_alter_faminfo_pdf_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faminfo',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, upload_to=famInfos.models.pdf_upload_to, validators=[utils.file_validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='faminfo',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to=famInfos.models.pdf_upload_to, validators=[utils.file_validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='faminfo',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, upload_to=famInfos.models.pdf_upload_to, validators=[utils.file_validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='faminfo',
            name='pdf_4',
            field=models.FileField(blank=True, null=True, upload_to=famInfos.models.pdf_upload_to, validators=[utils.file_validators.validate_pdf]),
        ),
    ]
