# Generated by Django 4.2 on 2024-08-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_guarantor_customuser_guarantor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='FAMILY',
            new_name='family',
        ),
        migrations.AddField(
            model_name='customuser',
            name='guarantor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
