# Generated by Django 4.2 on 2024-07-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_guarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='FAMILY',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
