# Generated by Django 4.2 on 2024-08-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_family_customuser_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen'),
        ),
    ]
