# Generated by Django 4.2 on 2024-08-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='family',
            field=models.CharField(blank=True, choices=[('kempe', 'Stammbaum Kempe'), ('huenten', 'Stammbaum Hünten')], max_length=50),
        ),
    ]
