# Generated by Django 4.2 on 2024-08-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_family_customuser_family_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='family_2',
            field=models.CharField(blank=True, choices=[('kempe', 'Stammbaum Kempe'), ('huenten', 'Stammbaum Hünten')], max_length=50, verbose_name='Stammbaum 2'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='family_1',
            field=models.CharField(blank=True, choices=[('kempe', 'Stammbaum Kempe'), ('huenten', 'Stammbaum Hünten')], max_length=50, verbose_name='Stammbaum 1'),
        ),
    ]
