# Generated by Django 4.2.15 on 2024-09-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='author_name',
            field=models.CharField(blank=True, default='Autor', max_length=255, null=True),
        ),
    ]
