# Generated by Django 4.2.15 on 2024-09-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_author_name'),
    ]

    operations = [
    ]
