# Generated by Django 4.2.15 on 2024-10-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alert_faminfo',
            field=models.BooleanField(default=False, verbose_name='FamInfo-Benachrichtigungen'),
        ),
    ]
