# Generated by Django 4.2.15 on 2024-10-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_alert_faminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alert_discussion',
            field=models.BooleanField(default=False, verbose_name='Diskussions-Benachrichtigungen'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='alert_info',
            field=models.BooleanField(default=False, verbose_name='Website-Info-Benachrichtigungen'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='alert_recipe',
            field=models.BooleanField(default=False, verbose_name='Rezept-Benachrichtigungen'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='alert_faminfo',
            field=models.BooleanField(default=False, verbose_name='Familen-Info-Benachrichtigungen'),
        ),
    ]
