# Generated by Django 4.2.15 on 2025-08-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_alert_discussion_customuser_alert_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alert_discussion',
            field=models.BooleanField(default=False, verbose_name='Stammfolge-Diskussion-Benachrichtigungen'),
        ),
    ]
