# Generated by Django 4.2 on 2024-08-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0002_alter_person_birt_date_alter_person_buri_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birt_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birt_plac',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Geburtsort'),
        ),
        migrations.AlterField(
            model_name='person',
            name='buri_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Beerdigungsdatum'),
        ),
        migrations.AlterField(
            model_name='person',
            name='buri_plac',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Beerdigungsort'),
        ),
        migrations.AlterField(
            model_name='person',
            name='chan_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Änderungsdatum'),
        ),
        migrations.AlterField(
            model_name='person',
            name='chan_date_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Änderungsdatum und -uhrzeit'),
        ),
        migrations.AlterField(
            model_name='person',
            name='chr_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taufe Adresse'),
        ),
        migrations.AlterField(
            model_name='person',
            name='chr_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taufe Datum'),
        ),
        migrations.AlterField(
            model_name='person',
            name='chr_plac',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taufe Ort'),
        ),
        migrations.AlterField(
            model_name='person',
            name='deat_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sterbedatum'),
        ),
        migrations.AlterField(
            model_name='person',
            name='deat_plac',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sterbeort'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_chil_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kinder der Familie 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_chil_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kinder der Familie 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_chil_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kinder der Familie 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_chil_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kinder der Familie 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_husb_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehemann der Familie 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_husb_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehemann der Familie 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_husb_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehemann der Familie 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_husb_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehemann der Familie 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_marr_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehe der Familie 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_marr_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehe der Familie 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_marr_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehe der Familie 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_marr_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehe der Familie 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_stat_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Familienstand 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_stat_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Familienstand 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_stat_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Familienstand 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_stat_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Familienstand 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_wife_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehefrau der Familie 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_wife_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehefrau der Familie 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_wife_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehefrau der Familie 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam_wife_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehefrau der Familie 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fath_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name des Vaters'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fath_refn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='#REFN des Vaters'),
        ),
        migrations.AlterField(
            model_name='person',
            name='givn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_date_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heiratsdatum 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_date_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heiratsdatum 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_date_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heiratsdatum 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_date_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heiratsdatum 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_plac_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heiratsort 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_plac_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heiratsort 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_plac_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heiratsort 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_plac_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heiratsort 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_spou_name_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name des Ehepartners 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_spou_name_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name des Ehepartners 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_spou_name_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name des Ehepartners 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_spou_name_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name des Ehepartners 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_spou_refn_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='#REFN des Ehepartners 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_spou_refn_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='#REFN des Ehepartners 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_spou_refn_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='#REFN des Ehepartners 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marr_spou_refn_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='#REFN des Ehepartners 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='moth_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name der Mutter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='moth_refn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='#REFN der Mutter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_marnm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ehename'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_nick',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spitzname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_npfx',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Namenspräfix'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_rufname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rufname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objektdatei 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objektdatei 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objektdatei 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objektdatei 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objektdatei 5'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objektdatei 6'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_titl_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objekttitel 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_titl_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objekttitel 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_titl_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objekttitel 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_titl_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objekttitel 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_titl_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objekttitel 5'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_titl_6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objekttitel 6'),
        ),
        migrations.AlterField(
            model_name='person',
            name='occu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Beruf'),
        ),
        migrations.AlterField(
            model_name='person',
            name='refn',
            field=models.CharField(max_length=255, verbose_name='#REFN'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reli',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sour',
            field=models.TextField(blank=True, null=True, verbose_name='Quelle'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UID'),
        ),
    ]
