# Generated by Django 4.2 on 2024-08-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0003_alter_person_birt_date_alter_person_birt_plac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='obje_file_1',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Bilddatei 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bilddatei 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bilddatei 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bilddatei 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bilddatei 5'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bilddatei 6'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_titl_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bildtitel 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_titl_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bildtitel 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_titl_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bildtitel 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_titl_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bildtitel 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_titl_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bildtitel 5'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_titl_6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bildtitel 6'),
        ),
    ]
