# Generated by Django 4.2 on 2024-08-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0004_alter_person_obje_file_1_alter_person_obje_file_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='obje_file_2',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Bilddatei 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_3',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Bilddatei 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_4',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Bilddatei 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_5',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Bilddatei 5'),
        ),
        migrations.AlterField(
            model_name='person',
            name='obje_file_6',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Bilddatei 6'),
        ),
    ]
