# Generated by Django 4.2 on 2024-08-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0007_alter_person_obje_file_1_alter_person_obje_file_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='confidential',
            field=models.CharField(choices=[('no', 'Nein'), ('restricted', 'Eingeschränkt'), ('yes', 'Ja')], default='no', max_length=10, verbose_name='Vertraulichkeit'),
        ),
    ]
