# Generated by Django 4.2 on 2024-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0008_person_confidential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='person',
            name='deat_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sterbedatum'),
        ),
    ]
