# Generated by Django 4.2 on 2024-08-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0009_alter_person_birt_date_alter_person_deat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birt_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='person',
            name='deat_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sterbedatum'),
        ),
    ]
