# Generated by Django 4.2 on 2024-08-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0011_remove_person_confidential'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='confidential',
            field=models.CharField(choices=[('no', 'Nein'), ('restricted', 'Eingeschränkt'), ('yes', 'Ja')], default='no', max_length=10, verbose_name='Vertraulichkeit'),
        ),
    ]
