# Generated by Django 4.2 on 2024-08-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0012_person_confidential'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date_formatted',
            field=models.DateField(blank=True, null=True, verbose_name='Formatiertes Geburtsdatum'),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date_formatted',
            field=models.DateField(blank=True, null=True, verbose_name='Formatiertes Sterbedatum'),
        ),
    ]
