# Generated by Django 4.2 on 2024-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0013_person_birth_date_formatted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date_formatted',
            field=models.DateField(blank=True, null=True, verbose_name='Automatisch formatiertes Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_date_formatted',
            field=models.DateField(blank=True, null=True, verbose_name='Automatisch formatiertes Sterbedatum'),
        ),
    ]
