# Generated by Django 4.2 on 2024-08-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0016_remove_person_family_trees_person_family_tree_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fath_refn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_of', to='ancestors.person', verbose_name='#REFN des Vaters')),
                ('marr_spou_refn_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse1_of', to='ancestors.person', verbose_name='Ehepartner 1')),
                ('marr_spou_refn_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse2_of', to='ancestors.person', verbose_name='Ehepartner 2')),
                ('marr_spou_refn_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse3_of', to='ancestors.person', verbose_name='Ehepartner 3')),
                ('marr_spou_refn_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse4_of', to='ancestors.person', verbose_name='Ehepartner 4')),
                ('moth_refn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_of', to='ancestors.person', verbose_name='Mutter')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_data', to='ancestors.person')),
            ],
        ),
    ]
