# Generated by Django 4.2 on 2024-08-04 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0017_relateddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='relateddata',
            name='children_1',
            field=models.ManyToManyField(blank=True, related_name='children_of_spouse1', to='ancestors.person', verbose_name='Kinder aus Ehe 1'),
        ),
        migrations.AddField(
            model_name='relateddata',
            name='children_2',
            field=models.ManyToManyField(blank=True, related_name='children_of_spouse2', to='ancestors.person', verbose_name='Kinder aus Ehe 2'),
        ),
        migrations.AddField(
            model_name='relateddata',
            name='children_3',
            field=models.ManyToManyField(blank=True, related_name='children_of_spouse3', to='ancestors.person', verbose_name='Kinder aus Ehe 3'),
        ),
        migrations.AddField(
            model_name='relateddata',
            name='children_4',
            field=models.ManyToManyField(blank=True, related_name='children_of_spouse4', to='ancestors.person', verbose_name='Kinder aus Ehe 4'),
        ),
        migrations.AlterField(
            model_name='relateddata',
            name='fath_refn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_of', to='ancestors.person', verbose_name='Vater'),
        ),
    ]
