# Generated by Django 4.2 on 2024-08-04 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ancestors', '0019_relateddata_fam_stat_1_relateddata_fam_stat_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_persons', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller'),
        ),
        migrations.AddField(
            model_name='person',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellungsdatum'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_persons', to=settings.AUTH_USER_MODEL, verbose_name='Letzte Änderung durch'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Letzte Änderung'),
        ),
    ]
