# Generated by Django 4.2 on 2024-08-04 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0020_person_created_by_person_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sour',
            field=models.TextField(blank=True, null=True, verbose_name='Quellen'),
        ),
    ]
