# Generated by Django 4.2 on 2024-08-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0021_alter_person_last_modified_date_alter_person_sour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedData',
            new_name='Relation',
        ),
    ]
