# Generated by Django 4.2 on 2024-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0022_rename_relateddata_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='refn',
            field=models.CharField(max_length=255, unique=True, verbose_name='#REFN'),
        ),
    ]
