# Generated by Django 4.2 on 2024-08-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0024_alter_person_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='Name'),
        ),
    ]
