# Generated by Django 4.2 on 2024-08-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0025_alter_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='family_tree_1',
            new_name='family_1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='family_tree_2',
            new_name='family_2',
        ),
    ]
