# Generated by Django 4.2.15 on 2024-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0027_alter_person_family_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family_1',
            field=models.CharField(choices=[('kempe', 'Stammbaum Kempe'), ('huenten', 'Stammbaum Hünten')], max_length=100, verbose_name='Stammbaum 1'),
        ),
    ]
