from django.db import models

class Person(models.Model):
    refn = models.CharField(max_length=255, verbose_name='#REFN')
    name = models.CharField(max_length=255, verbose_name='NAME')
    fath_name = models.CharField(max_length=255, verbose_name='FATH.NAME', null=True, blank=True)
    fath_refn = models.CharField(max_length=255, verbose_name='FATH.#REFN', null=True, blank=True)
    moth_name = models.CharField(max_length=255, verbose_name='MOTH.NAME', null=True, blank=True)
    moth_refn = models.CharField(max_length=255, verbose_name='MOTH.#REFN', null=True, blank=True)
    uid = models.CharField(max_length=255, verbose_name='_UID', null=True, blank=True)
    surn = models.CharField(max_length=255, verbose_name='SURN', null=True, blank=True)
    givn = models.CharField(max_length=255, verbose_name='GIVN', null=True, blank=True)
    sex = models.CharField(max_length=10, verbose_name='SEX', null=True, blank=True)
    occu = models.CharField(max_length=255, verbose_name='OCCU', null=True, blank=True)
    chan_date = models.DateField(verbose_name='CHAN.DATE', null=True, blank=True)
    chan_date_time = models.CharField(max_length=255, verbose_name='CHAN.DATE.TIME', null=True, blank=True)
    birt_date = models.DateField(verbose_name='BIRT.DATE', null=True, blank=True)
    birt_plac = models.CharField(max_length=255, verbose_name='BIRT.PLAC', null=True, blank=True)
    deat_date = models.DateField(verbose_name='DEAT.DATE', null=True, blank=True)
    deat_plac = models.CharField(max_length=255, verbose_name='DEAT.PLAC', null=True, blank=True)
    note = models.TextField(verbose_name='NOTE', null=True, blank=True)
    chr_date = models.DateField(verbose_name='CHR.DATE', null=True, blank=True)
    chr_plac = models.CharField(max_length=255, verbose_name='CHR.PLAC', null=True, blank=True)
    buri_date = models.DateField(verbose_name='BURI.DATE', null=True, blank=True)
    buri_plac = models.CharField(max_length=255, verbose_name='BURI.PLAC', null=True, blank=True)
    name_rufname = models.CharField(max_length=255, verbose_name='NAME._RUFNAME', null=True, blank=True)
    name_npfx = models.CharField(max_length=255, verbose_name='NAME.NPFX', null=True, blank=True)
    sour = models.TextField(verbose_name='SOUR', null=True, blank=True)
    name_nick = models.CharField(max_length=255, verbose_name='NAME.NICK', null=True, blank=True)
    name_marnm = models.CharField(max_length=255, verbose_name='NAME._MARNM', null=True, blank=True)
    chr_addr = models.CharField(max_length=255, verbose_name='CHR.ADDR', null=True, blank=True)
    reli = models.CharField(max_length=255, verbose_name='RELI', null=True, blank=True)
    
    # Marriage and family information (repeated fields for each spouse and family)
    marr_spou_name_1 = models.CharField(max_length=255, verbose_name='MARR.SPOU.NAME.1', null=True, blank=True)
    marr_spou_refn_1 = models.CharField(max_length=255, verbose_name='MARR.SPOU.#REFN.1', null=True, blank=True)
    fam_husb_1 = models.CharField(max_length=255, verbose_name='FAM.HUSB.1', null=True, blank=True)
    fam_wife_1 = models.CharField(max_length=255, verbose_name='FAM.WIFE.1', null=True, blank=True)
    marr_date_1 = models.DateField(verbose_name='MARR.DATE.1', null=True, blank=True)
    marr_plac_1 = models.CharField(max_length=255, verbose_name='MARR.PLAC.1', null=True, blank=True)
    fam_chil_1 = models.CharField(max_length=255, verbose_name='FAM.CHIL.1', null=True, blank=True)
    fam_marr_1 = models.CharField(max_length=255, verbose_name='FAM.MARR.1', null=True, blank=True)
    fam_stat_1 = models.CharField(max_length=255, verbose_name='FAM._STAT.1', null=True, blank=True)
    fam_marr_1 = models.CharField(max_length=255, verbose_name='FAM._MARR.1', null=True, blank=True)
    
    # Additional fields for other spouses/families (repeating the same pattern as above)
    marr_spou_name_2 = models.CharField(max_length=255, verbose_name='MARR.SPOU.NAME.2', null=True, blank=True)
    marr_spou_refn_2 = models.CharField(max_length=255, verbose_name='MARR.SPOU.#REFN.2', null=True, blank=True)
    fam_husb_2 = models.CharField(max_length=255, verbose_name='FAM.HUSB.2', null=True, blank=True)
    fam_wife_2 = models.CharField(max_length=255, verbose_name='FAM.WIFE.2', null=True, blank=True)
    marr_date_2 = models.DateField(verbose_name='MARR.DATE.2', null=True, blank=True)
    marr_plac_2 = models.CharField(max_length=255, verbose_name='MARR.PLAC.2', null=True, blank=True)
    fam_chil_2 = models.CharField(max_length=255, verbose_name='FAM.CHIL.2', null=True, blank=True)
    fam_marr_2 = models.CharField(max_length=255, verbose_name='FAM.MARR.2', null=True, blank=True)
    fam_stat_2 = models.CharField(max_length=255, verbose_name='FAM._STAT.2', null=True, blank=True)
    fam_marr_2 = models.CharField(max_length=255, verbose_name='FAM._MARR.2', null=True, blank=True)
    
    # Repeat similar fields for third and fourth spouses/families
    marr_spou_name_3 = models.CharField(max_length=255, verbose_name='MARR.SPOU.NAME.3', null=True, blank=True)
    marr_spou_refn_3 = models.CharField(max_length=255, verbose_name='MARR.SPOU.#REFN.3', null=True, blank=True)
    fam_husb_3 = models.CharField(max_length=255, verbose_name='FAM.HUSB.3', null=True, blank=True)
    fam_wife_3 = models.CharField(max_length=255, verbose_name='FAM.WIFE.3', null=True, blank=True)
    marr_date_3 = models.DateField(verbose_name='MARR.DATE.3', null=True, blank=True)
    marr_plac_3 = models.CharField(max_length=255, verbose_name='MARR.PLAC.3', null=True, blank=True)
    fam_chil_3 = models.CharField(max_length=255, verbose_name='FAM.CHIL.3', null=True, blank=True)
    fam_marr_3 = models.CharField(max_length=255, verbose_name='FAM.MARR.3', null=True, blank=True)
    fam_stat_3 = models.CharField(max_length=255, verbose_name='FAM._STAT.3', null=True, blank=True)
    fam_marr_3 = models.CharField(max_length=255, verbose_name='FAM._MARR.3', null=True, blank=True)
    
    marr_spou_name_4 = models.CharField(max_length=255, verbose_name='MARR.SPOU.NAME.4', null=True, blank=True)
    marr_spou_refn_4 = models.CharField(max_length=255, verbose_name='MARR.SPOU.#REFN.4', null=True, blank=True)
    fam_husb_4 = models.CharField(max_length=255, verbose_name='FAM.HUSB.4', null=True, blank=True)
    fam_wife_4 = models.CharField(max_length=255, verbose_name='FAM.WIFE.4', null=True, blank=True)
    marr_date_4 = models.DateField(verbose_name='MARR.DATE.4', null=True, blank=True)
    marr_plac_4 = models.CharField(max_length=255, verbose_name='MARR.PLAC.4', null=True, blank=True)
    fam_chil_4 = models.CharField(max_length=255, verbose_name='FAM.CHIL.4', null=True, blank=True)
    fam_marr_4 = models.CharField(max_length=255, verbose_name='FAM.MARR.4', null=True, blank=True)
    fam_stat_4 = models.CharField(max_length=255, verbose_name='FAM._STAT.4', null=True, blank=True)
    fam_marr_4 = models.CharField(max_length=255, verbose_name='FAM._MARR.4', null=True, blank=True)
    
    # Object files and titles
    obje_file_1 = models.CharField(max_length=255, verbose_name='OBJE.FILE.1', null=True, blank=True)
    obje_titl_1 = models.CharField(max_length=255, verbose_name='OBJE.TITL.1', null=True, blank=True)
    obje_file_2 = models.CharField(max_length=255, verbose_name='OBJE.FILE.2', null=True, blank=True)
    obje_titl_2 = models.CharField(max_length=255, verbose_name='OBJE.TITL.2', null=True, blank=True)
    obje_file_3 = models.CharField(max_length=255, verbose_name='OBJE.FILE.3', null=True, blank=True)
    obje_titl_3 = models.CharField(max_length=255, verbose_name='OBJE.TITL.3', null=True, blank=True)
    obje_file_4 = models.CharField(max_length=255, verbose_name='OBJE.FILE.4', null=True, blank=True)
    obje_titl_4 = models.CharField(max_length=255, verbose_name='OBJE.TITL.4', null=True, blank=True)
    obje_file_5 = models.CharField(max_length=255, verbose_name='OBJE.FILE.5', null=True, blank=True)
    obje_titl_5 = models.CharField(max_length=255, verbose_name='OBJE.TITL.5', null=True, blank=True)
    obje_file_6 = models.CharField(max_length=255, verbose_name='OBJE.FILE.6', null=True, blank=True)
    obje_titl_6 = models.CharField(max_length=255, verbose_name='OBJE.TITL.6', null=True, blank=True)

    def __str__(self):
        return self.name

