from django.db import models

class Person(models.Model):
    refn = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    fath_name = models.CharField(max_length=255, null=True, blank=True)
    fath_refn = models.CharField(max_length=255, null=True, blank=True)
    moth_name = models.CharField(max_length=255, null=True, blank=True)
    moth_refn = models.CharField(max_length=255, null=True, blank=True)
    uid = models.CharField(max_length=255, null=True, blank=True)
    surn = models.CharField(max_length=255, null=True, blank=True)
    givn = models.CharField(max_length=255, null=True, blank=True)
    sex = models.CharField(max_length=10, null=True, blank=True)
    occu = models.CharField(max_length=255, null=True, blank=True)
    chan_date = models.DateField(null=True, blank=True)
    chan_date_time = models.CharField(max_length=255, null=True, blank=True)
    birt_date = models.DateField(null=True, blank=True)
    birt_plac = models.CharField(max_length=255, null=True, blank=True)
    deat_date = models.DateField(null=True, blank=True)
    deat_plac = models.CharField(max_length=255, null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    chr_date = models.DateField(null=True, blank=True)
    chr_plac = models.CharField(max_length=255, null=True, blank=True)
    buri_date = models.DateField(null=True, blank=True)
    buri_plac = models.CharField(max_length=255, null=True, blank=True)
    name_rufname = models.CharField(max_length=255, null=True, blank=True)
    name_npfx = models.CharField(max_length=255, null=True, blank=True)
    sour = models.TextField(null=True, blank=True)
    name_nick = models.CharField(max_length=255, null=True, blank=True)
    name_marnm = models.CharField(max_length=255, null=True, blank=True)
    chr_addr = models.CharField(max_length=255, null=True, blank=True)
    reli = models.CharField(max_length=255, null=True, blank=True)
    
    # Marriage and family information (repeated fields for each spouse and family)
    marr_spou_name_1 = models.CharField(max_length=255, null=True, blank=True)
    marr_spou_refn_1 = models.CharField(max_length=255, null=True, blank=True)
    fam_husb_1 = models.CharField(max_length=255, null=True, blank=True)
    fam_wife_1 = models.CharField(max_length=255, null=True, blank=True)
    marr_date_1 = models.DateField(null=True, blank=True)
    marr_plac_1 = models.CharField(max_length=255, null=True, blank=True)
    fam_chil_1 = models.CharField(max_length=255, null=True, blank=True)
    fam_marr_1 = models.CharField(max_length=255, null=True, blank=True)
    fam_stat_1 = models.CharField(max_length=255, null=True, blank=True)
    fam_marr_1 = models.CharField(max_length=255, null=True, blank=True)
    
    # Additional fields for other spouses/families (repeating the same pattern as above)
    marr_spou_name_2 = models.CharField(max_length=255, null=True, blank=True)
    marr_spou_refn_2 = models.CharField(max_length=255, null=True, blank=True)
    fam_husb_2 = models.CharField(max_length=255, null=True, blank=True)
    fam_wife_2 = models.CharField(max_length=255, null=True, blank=True)
    marr_date_2 = models.DateField(null=True, blank=True)
    marr_plac_2 = models.CharField(max_length=255, null=True, blank=True)
    fam_chil_2 = models.CharField(max_length=255, null=True, blank=True)
    fam_marr_2 = models.CharField(max_length=255, null=True, blank=True)
    fam_stat_2 = models.CharField(max_length=255, null=True, blank=True)
    fam_marr_2 = models.CharField(max_length=255, null=True, blank=True)
    
    # Repeat similar fields for third and fourth spouses/families
    marr_spou_name_3 = models.CharField(max_length=255, null=True, blank=True)
    marr_spou_refn_3 = models.CharField(max_length=255, null=True, blank=True)
    fam_husb_3 = models.CharField(max_length=255, null=True, blank=True)
    fam_wife_3 = models.CharField(max_length=255, null=True, blank=True)
    marr_date_3 = models.DateField(null=True, blank=True)
    marr_plac_3 = models.CharField(max_length=255, null=True, blank=True)
    fam_chil_3 = models.CharField(max_length=255, null=True, blank=True)
    fam_marr_3 = models.CharField(max_length=255, null=True, blank=True)
    fam_stat_3 = models.CharField(max_length=255, null=True, blank=True)
    fam_marr_3 = models.CharField(max_length=255, null=True, blank=True)
    
    marr_spou_name_4 = models.CharField(max_length=255, null=True, blank=True)
    marr_spou_refn_4 = models.CharField(max_length=255, null=True, blank=True)
    fam_husb_4 = models.CharField(max_length=255, null=True, blank=True)
    fam_wife_4 = models.CharField(max_length=255, null=True, blank=True)
    marr_date_4 = models.DateField(null=True, blank=True)
    marr_plac_4 = models.CharField(max_length=255, null=True, blank=True)
    fam_chil_4 = models.CharField(max_length=255, null=True, blank=True)
    fam_marr_4 = models.CharField(max_length=255, null=True, blank=True)
    fam_stat_4 = models.CharField(max_length=255, null=True, blank=True)
    fam_marr_4 = models.CharField(max_length=255, null=True, blank=True)
    
    # Object files and titles
    obje_file_1 = models.CharField(max_length=255, null=True, blank=True)
    obje_titl_1 = models.CharField(max_length=255, null=True, blank=True)
    obje_file_2 = models.CharField(max_length=255, null=True, blank=True)
    obje_titl_2 = models.CharField(max_length=255, null=True, blank=True)
    obje_file_3 = models.CharField(max_length=255, null=True, blank=True)
    obje_titl_3 = models.CharField(max_length=255, null=True, blank=True)
    obje_file_4 = models.CharField(max_length=255, null=True, blank=True)
    obje_titl_4 = models.CharField(max_length=255, null=True, blank=True)
    obje_file_5 = models.CharField(max_length=255, null=True, blank=True)
    obje_titl_5 = models.CharField(max_length=255, null=True, blank=True)
    obje_file_6 = models.CharField(max_length=255, null=True, blank=True)
    obje_titl_6 = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name
