# Generated by Django 4.2 on 2024-08-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_instructions_recipe_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='family_1',
            field=models.CharField(blank=True, choices=[('kempe', 'Stammbaum Kempe'), ('huenten', 'Stammbaum Hünten')], max_length=50, verbose_name='Stammbaum 1'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='family_2',
            field=models.CharField(blank=True, choices=[('kempe', 'Stammbaum Kempe'), ('huenten', 'Stammbaum Hünten')], max_length=50, verbose_name='Stammbaum 2'),
        ),
    ]
