# Generated by Django 4.2 on 2024-08-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_family_1_recipe_family_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='family_2',
            field=models.CharField(blank=True, choices=[('kempe', 'Stammbaum Kempe'), ('huenten', 'Stammbaum Hünten')], max_length=50, null=True, verbose_name='Stammbaum 2'),
        ),
    ]
