# Generated by Django 4.2 on 2024-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_family_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_1_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/thumbnails/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_2_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/thumbnails/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_3_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/thumbnails/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_4_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/thumbnails/'),
        ),
    ]
