# Generated by Django 4.2.15 on 2024-09-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_family_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='family_1',
            field=models.CharField(choices=[('kempe', 'Stammbaum Kempe'), ('huenten', 'Stammbaum Hünten')], max_length=100, verbose_name='Stammbaum 1'),
        ),
    ]
