# Generated by Django 4.2 on 2024-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_discussionentry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionentry',
            name='image_1',
            field=models.FileField(blank=True, null=True, upload_to='discussions/'),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='image_1_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='discussions/thumbnails/'),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='discussions/'),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='image_2_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='discussions/thumbnails/'),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='discussions/'),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='image_3_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='discussions/thumbnails/'),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='image_4',
            field=models.FileField(blank=True, null=True, upload_to='discussions/'),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='image_4_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='discussions/thumbnails/'),
        ),
    ]
