# Generated by Django 4.2.15 on 2025-08-29 10:23

import discussions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_discussionentry_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionentry',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, upload_to=discussions.models.pdf_upload_to),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='pdf_1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to=discussions.models.pdf_upload_to),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='pdf_2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, upload_to=discussions.models.pdf_upload_to),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='pdf_3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='pdf_4',
            field=models.FileField(blank=True, null=True, upload_to=discussions.models.pdf_upload_to),
        ),
        migrations.AddField(
            model_name='discussionentry',
            name='pdf_4_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
