# Generated by Django 5.2.16 on 2026-08-07 14:34

import discussions.models
import utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_discussionentry_pdf_1_discussionentry_pdf_1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionentry',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, upload_to=discussions.models.pdf_upload_to, validators=[utils.file_validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='discussionentry',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to=discussions.models.pdf_upload_to, validators=[utils.file_validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='discussionentry',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, upload_to=discussions.models.pdf_upload_to, validators=[utils.file_validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='discussionentry',
            name='pdf_4',
            field=models.FileField(blank=True, null=True, upload_to=discussions.models.pdf_upload_to, validators=[utils.file_validators.validate_pdf]),
        ),
    ]
