# Generated by Django 4.2.15 on 2024-09-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0005_info_image_1_thumbnail_info_image_2_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='family_1',
            field=models.CharField(choices=[('kempe', 'Stammbaum Kempe'), ('huenten', 'Stammbaum Hünten')], default='kempe', max_length=100, verbose_name='Stammbaum 1'),
        ),
    ]
