# Generated by Django 5.2.16 on 2026-08-07 14:34

import infos.models
import utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0008_info_pdf_1_info_pdf_1_name_info_pdf_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, upload_to=infos.models.pdf_upload_to, validators=[utils.file_validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='info',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to=infos.models.pdf_upload_to, validators=[utils.file_validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='info',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, upload_to=infos.models.pdf_upload_to, validators=[utils.file_validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='info',
            name='pdf_4',
            field=models.FileField(blank=True, null=True, upload_to=infos.models.pdf_upload_to, validators=[utils.file_validators.validate_pdf]),
        ),
    ]
